### ISSUE TITLE
전적검색 관련

### ISSUE THREAD

**Issue by Jihyun0511** [Insiro/Lisa-Discord-Bot#1]
!!전적 <닉네임>을 입력했을 때
Failed to load data
plz check args
라고 나옵니다. 무슨 문제인가요?

**Comment by Insiro** [comment]
전적 불려오는데 실패했을 경우의 출력입니다.
닉네임 을 확인해주시거나, 사퍼 / 네오플api 서버가 작동을 안할경우입니다
