### ISSUE TITLE
채널 ID 추가가 안됩니다.

### ISSUE THREAD

**Issue by ainshard** [Insiro/Lisa-Discord-Bot#7]
명령에 적혀있는 채널ID란 디스코드기준 글을 뿌려줄 채널의 이름 즉 "#채널명" 인가요?

시도해 본 명령은 다음과 같습니다.

!!설정 채널 #사이퍼즈
!!설정 채널 "#사이퍼즈 의 초대코드"

채널 설정이안되서 
구독역시 진행이 안되는 것 같은데, 구독 하는 방법도 미리 궁금합니다. 

답변 감사합니다.

**Comment by Insiro** [comment]
군대에 있어서 확인이 늦어졌네요.
"#채널 이름"으로 채널 id 가져오도록 향후 수정하겠습니다.

채널 아이디는 채팅채널 이름에 우클릭을 하시면  ID 복사하기 있습니다.
![image](https://user-images.githubusercontent.com/19542951/116783198-5fa8a100-aac8-11eb-865b-25a0f9b86fce.png)
그 값을 넣으면 됩니다

**Comment by ainshard** [comment]
p{margin-top:0;margin-bottom:0}
    


    답변 감사합니다. 제가 채널을 만들었고 권한이 다 있는 상태 인데요.. 저는 채널 아이디 복제가 안보입니다. 달리 확인 방법은 없는 건가요?? ---- 원본 메일 ----보낸 사람 : ***@***.***>받는 사람 : ***@***.***>참조 : ***@***.***>, ***@***.***>날짜 : 21.05.01 21:59 GMT +0900제목 : Re: [Insiro/cyphers-Discord-Bot] 채널 ID 추가가 안됩니다. (#7)

군대에 있어서 확인이 늦어졌네요.

"#채널 이름"으로 채널 id 가져오도록 향후 수정하겠습니다.

채널 아이디는 채팅채널 이름에 우클릭을 하시면  ID 복사하기 있습니다.



그 값을 넣으면 됩니다



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Insiro/cyphers-Discord-Bot/issues/7#issuecomment-830628709",

"url": "https://github.com/Insiro/cyphers-Discord-Bot/issues/7#issuecomment-830628709",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Insiro** [comment]
디스코드 설정 -> 앱설정 -> 고급 -> 개발자 모드를 한번 켜보시겠나요??

**Comment by ainshard** [comment]
p{margin-top:0;margin-bottom:0}
    


    긴 시간 기다림이 허무하네요.. ^^; 빠른 회신 감사합니다. 확인 했습니다. 건강하세요! ---- 원본 메일 ----보낸 사람 : ***@***.***>받는 사람 : ***@***.***>참조 : ***@***.***>, ***@***.***>날짜 : 21.05.02 16:21 GMT +0900제목 : Re: [Insiro/cyphers-Discord-Bot] 채널 ID 추가가 안됩니다. (#7)

디스코드 설정 -> 앱설정 -> 고급 -> 개발자 모드를 한번 켜보시겠나요??



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Insiro/cyphers-Discord-Bot/issues/7#issuecomment-830764099",

"url": "https://github.com/Insiro/cyphers-Discord-Bot/issues/7#issuecomment-830764099",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
